# Generated by Django 5.0.4 on 2024-05-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('post_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
    ]
