# Generated by Django 5.0.4 on 2024-06-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_followings_follower'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followings',
            unique_together={('follower', 'followed')},
        ),
    ]
